name: Deploy to Pages repo

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "0.151.0"
          extended: true

      - name: Build
        run: hugo --minify --gc

      # 关键：用 deploy_key 推送到外部仓库
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }} # ← 改这里
          external_repository: MinoGeorge/MinoGeorge.github.io # ← 你的 Pages 库
          publish_branch: main # ← Pages 库分支
          publish_dir: ./public # Hugo 默认输出目录
